### PR TITLE
Add AppImage support for linux distributions

### LINKED ISSUE #36: Official Flatpak, deb, and AUR versions
Would it be possible to have official flatpak, .deb, and AUR versions of the RuneLite launcher? It's definitely not absolutely needed since it's already very easy to just get the .jar from the website, but this would let people download the launcher straight from various software managers.

Also please forgive me if I'm misunderstanding how these formats work, I'm still pretty new to the Linux ecosystem.

### PR DESCRIPTION
**Pull request by deathbeam**
Based on this wiki page:
https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps

Closes #21 
Closes #36 

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Results:

```
$ ls -lh target/native/linux64/
Alias tip: ll target/native/linux64/
total 53M
drwxr-xr-x 3 vagrant vagrant 4.0K Feb 12 10:31 RuneLite.AppDir
-rwxr-xr-x 1 vagrant vagrant  53M Feb 12 10:31 RuneLite.AppImage
```

```
$ ./target/native/linux64/RuneLite.AppImage
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
10:46:39,673 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:46:39,673 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback. 
```

### CODE REVIEW

**Comment by Adam-** [comment]
To integrate better should this also use `--nojvm`?

**Comment by deathbeam** [comment]
It is already using nojvm

**Comment by deathbeam** [comment]
Looks like the metadata change works just fine:

```
$ ls -lh target/native/linux64/RuneLite.AppDir
Alias tip: ll target/native/linux64/RuneLite.AppDir
total 2.5M
drwxr-xr-x 4 deathbeam deathbeam 4.0K Feb 13 08:22 jre
drwxr-xr-x 3 deathbeam deathbeam 4.0K Feb 13 08:22 usr
-rw-r--r-- 1 deathbeam deathbeam  305 Feb 13 08:22 config.json
-rwxr--r-- 1 deathbeam deathbeam  85K Feb 13 08:22 RuneLite
-rw-r--r-- 1 deathbeam deathbeam  133 Feb 13 08:19 runelite.desktop
-rw-r--r-- 1 deathbeam deathbeam 2.4M Feb 13 08:22 RuneLite.jar
-rw-r--r-- 1 deathbeam deathbeam  35K Feb 13 08:19 runelite.png
```

**Comment by deathbeam** [comment]
Updated to use resource filtering

**Pull request merged**
