### PR TITLE
Update style and increase resolution of macOS icons

### LINKED ISSUE #44: Improve resolution of launcher icon, macOS
Apple's guidelines for app icons request that artwork be provided at a variety of sizes, including up to 1024x1024 for use on HiDPI displays (towards the bottom of [this](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) page). At the moment, the icons provided for macOS in `icons.icns` only go up to 128 x 128, resulting in blurry/pixelated artwork appearing in a few places throughout the system, including in the application switcher, spotlight search, and in Finder.

Using the .psd file provided [here](https://github.com/runelite/static.runelite.net/blob/661a32d4d03918b7fbf05931fa5169cbfd11c28b/assets/runelite_icon.psd), I created a new `.icns` file, though due to the source file being only 1024x1024, I was not able to zoom in in order to mirror the appearance of the current icon. Substituting in the new `.icns` file results in much clearer artwork throughout the system.

I've attached below a comparison between 128x128 icons pulled from the original and new .icns files to illustrate the differences between them. I can further round the corners to match the current style, though I am not sure how to approach the issue of zoom.

New version:
icons-6 dragged
Current version:
runelite-1 dragged

Attached below is the new .icns file I made, if anyone wishes to see how the icons compare in terms of either blurriness or style.
[new_icons.icns.zip](https://github.com/runelite/launcher/files/2780863/new_icons.icns.zip)

### PR DESCRIPTION
**Pull request by TylerADavis**
This PR Fixes #44 by increasing the resolution of icons on macOS from the original 128x128 maximum to up to 512x512@2x (1024x1024), resulting in much clearer icons in the Finder, dock, and in the quickswitcher. This PR also brings the icons in line with Apple's latest [icon design guidelines for mac](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon) with the adoption of a new shape and a drop shadow. Some examples are shown below:

Previous highest resolution icon viewed through finder:
image

New equivalent icon:

image

New icon in dock, note uniform style:
image

### CODE REVIEW

**Comment by TylerADavis** [comment]
@devLotto Adam recommended I ask you to see how much this PR affects the size of the final DMG for distribution generated by `build-osx.sh`. The new `.icns` file is 1.9MB larger than the old one, and it's not clear how large an impact that would have within the compressed dmg.

I tried building the dmg myself, but I was getting 40-42 MB dmgs vs the 32 MB dmg file from runelite.net .

**Comment by devLotto** [comment]
@TylerADavis For me using your icns file increases the DMG file size by 1.9MB. I don't do any special compressing other than what the code in build-osx.sh might do.

**Comment by TylerADavis** [comment]
@devLotto Thanks for taking a look! I'd guess that the 30 vs 40 MB disparity is due to either using a different version of macOS or a different version of some dependency.

I've tried to reduce the size of `icons.icns` by first passing the images through [tinypng.com](tinypng.com), but I didn't have any success. While tinypng.com successfully dropped the size of the raw PNGs, reducing the size of `runelite.iconset` from 2MB to 700KB, creating `icons.icns` using the command `iconutil -c icns ./tiny_runelite.iconset` resulted in the file size returning to 2MB (70 KB  savings). I'm not very familiar with `iconutil`, but [the documentation](https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html) suggests that it should be compressing the images. Perhaps tinypng is using a compression format incompatible with `icns` or `iconutil` is automatically converting to a less efficient compression scheme.

@Adam- do you think the 2MB size increase is fine (+6% to download size, +1.2% to size of final launcher), or would you still prefer something smaller?

**Comment by devLotto** [comment]
@TylerADavis We decided that +2MB is a large size increase just for icons and that it would be better if the 512 and 512@2x versions were removed (bringing the .icns file down to ~500KB).

**Comment by TylerADavis** [comment]
Hi @devLotto , thank you for your feedback. I've removed both the 512x512 and 512x512@2x assets, dropping the size of the `.icns` file from 2.1 MB to 535 KB. Please let me know if there are any other changes you'd like to see.

**Comment by mmccoy37** [comment]
I have been setting this manually. Would love to see it OOTB in an upcoming release if there are no further blockers to merging.

**Pull request merged**
